### ISSUE TITLE
Two Broadlink Devices Config Not Working

### ISSUE THREAD

**Issue by polycat33** [kiwi-cam/homebridge-broadlink-rm#278]
My config file thus far isn't working to let me learn codes from either of my two Broadlink devices. 

{
    "platform": "BroadlinkRM",
    "name": "BroadlinkRM",
    "hosts": [
        {
            "address": "192.168.68.116",
            "mac": "24:DF:A7:4F:90:37",
            "isRFSupported": true,
            "isRM4": true
        },
        {
            "address": "192.168.68.114",
            "mac": "24:DF:A7:F0:DF:9F",
            "isRFSupported": false
        }
    ],
    "accessories": [
        {
            "name": "RF Blaster",
            "type": "learn-code",
            "host": "192.168.68.116"
        },
        {
            "name": "IR Blaster",
            "type": "learn-code",
            "host": "192.168.68.114"
        }
    ]
}

There are no errors in my status log, but I do see something funny. The Mac addresses are reported weirdly, adding colons between the two hex digits if the second hex digit is a letter. I tried using dashes instead of colons (which is how my router reports it) but it just did the same thing wish dashes that it did with colons. 

[3/25/2021, 03:03:03] Homebridge v1.3.4 (Homebridge D3EE) is running on port 51460.
[3/25/2021, 03:03:03] [BroadlinkRM] [INFO] Discovered Manual RM4 Pro Device (2227) at 192.168.68.116 (24::D:F::A7::4:F::90::3:7)
[3/25/2021, 03:03:03] [BroadlinkRM] [INFO] Discovered Manual RM Device (2221) at 192.168.68.114 (24::D:F::A7::F:0::DF::9:F)

What am I doing wrong? Thanks!!

**Comment by masterfordev** [comment]
Update to the beta version, or remove the mac address, just use the IP and will work, thats because have a bug on get mac (this was fixed in the beta version).

**Comment by polycat33** [comment]
So the error reported in the status log that the Mac is missing can just be ignored? 

EDIT: Without the Mac addresses the homebridge plugin is reporting as taking a long time to load, and it prevents everything else from coming online.

How do I get the beta version of the plugin?

**Comment by masterfordev** [comment]
`install -g homebridge-broadlink-rm-pro@beta`

The log dont report an error. Just say devices discovered. You can ignore it.

**Comment by polycat33** [comment]
Ok, great, I'm not getting errors and the Mac address is reporting correctly. BUT I'm still not able to use my learn buttons. I don't get an error when I click them, but I also don't get the light on the broadlink device indicating it's listening for a signal, nor does it pick up a signal if I try even without the listening light. Thoughts?

EDIT: to be clear, in the log I see the lines about learning being enabled, and then it times out after 10 seconds.

**Comment by masterfordev** [comment]
Can share the log when you are trying to scan?

**Comment by kiwi-cam** [comment]
Even better, add `"debug": true` to your config first and restart. That'll show if the commands to enter the scan is being sent correctly.

**Comment by polycat33** [comment]
::Facepalm:: Turns out I had the IPs swapped in my config, I noticed the little one (IR) listening when I clicked listen for the big one (IR/RF). I double and tripled checked that, but turns out I named them wrong in my router app, so the mistake goes way back.
