### ISSUE TITLE
New humidifier bugs

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#97]
1. when humidifierOnly is true and the device is off, the device status in HK keeps saying “Rising to x %”  instead of “off” (I think current humidity status is not updated to inactive when turning off the device)
2. Auto off option is not working

_Originally posted by @CyberMrProper in https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/90#issuecomment-716860414_

**Comment by Faisalthe01** [comment]
Hey @kiwi-cam, i was able to achieve the no .1 point by moving SwitchState from Fan to Humidifier and then adding if switchState is 0 then then the rest 0 and that did the trick for me.

  
 ```
   async setSwitchState (hexData, previousValue) {
    const { config, state, serviceManager } = this;

    if (!this.state.switchState) {
      this.lastFanSpeed = undefined;
    }
	  if (state.switchState == 0){
        state.currentState = 0;
		state.targetState = 0;
	  }
   serviceManager.refreshCharacteristicUI(Characteristic.CurrentHumidifierDehumidifierState);

    super.setSwitchState(hexData, previousValue);
  }
```

2. I have an automation for auto-off and that works fine.

**Comment by CyberMrProper** [comment]
The auto off option is the one you can configure in the accessory. It works for the Fan accessory, but in Humidifier does no. The log seems to indicate that the switch button is turned off, but in HK it stays on. Hope that clarifies the issue.

Eg:
 "enableAutoOff": true,
 "onDuration": 60,

**Comment by kiwi-cam** [comment]
Could you try the latest Beta (homebridge-broadlink-rm-pro@4.3.6-beta.0)? I've had a bit of a tidy up of a few things and 1. should be resolved now... hopefully 2. as well.

**Comment by CyberMrProper** [comment]
Thanks @kiwi-cam! I tried the beta, this is the result:

Issue 1 is half fixed, showing the right status when off, but when I turn it on, status says “set to x%” instead of “raising to x%”. Maybe when you turn on the device you need to put the humidifying/ dehumidifying / auto status and that will depend on the configuration (humidifierOnly, dehumidifierOnly, both)

Issue 2 still happening, enableAutoOff is not working.

**Comment by Faisalthe01** [comment]
@CyberMrProper can you go touch and hold on the tile and go in the accessory and turn on from there and see if it changes to Raising To or Lowering to?

**Comment by CyberMrProper** [comment]
@Faisalthe01 from inside the tile, it puts “rising to x%” just the fist time, if I turn it off and on again it goes to “set to x%”

**Comment by Faisalthe01** [comment]
Seems like Tile is not syncing correctly. If we turn it on from Tile it should turn on the Button inside the Tile right? Or the button should be turned on separately?

**Comment by CyberMrProper** [comment]
Also @kiwi-cam, with your last commit it started sending the hex code twice when turning on / off

**Comment by kiwi-cam** [comment]
The more I look at this, the more confused I get about why things are done the way they are. I think this comes from it's evolution from a dumb "always dehumidify" to a better device. 

I'm going to stop looking at this bug and look at a full overhaul... obviously that will take a little more time.  I'll keep you posted.

**Comment by kiwi-cam** [comment]
I've just pushed a new BETA, homebridge-broadlink-rm-pro@4.3.6-beta.2.  It's more of an Alpha than a beta. I'm expecting issues with the amount of changes made.  Could you try it out and let me know what you find?

I've also added a hexCode "fanOnly". The Accessory has three active states, Humidifying, Dehumidifying, and Idle. In Idle the device is on and the Fan is running but the Humidity isn't being managed. If this value isn't set, it'll send the off code. This could have unexpected results if the device doesn't turn on again when sent the other codes. Something to keep an eye on.

**Comment by CyberMrProper** [comment]
@kiwi-cam I've got:

(node:55830) UnhandledPromiseRejectionWarning: ReferenceError: serviceManager is not defined
    at HumidifierDehumidifierAccessory.updateDeviceState (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/humidifier-dehumidifier.js:141:7)

**Comment by CyberMrProper** [comment]
@kiwi-cam, besides the error in my previous comment, here are 3 more things. 

- **Case: humidifierOnly: true, current humidity 5:**  If the device is off, and target humidity is >5, status in the tile is rising to x%, if is below that number it says Off. It should say Off in both cases. Same happens if while is off, I enter the detail screen and adjust the target humidity (without turning it on).
- **"enableAutoOff": true, "onDuration": 60** Still not working (I think it has to do with the fact that Switch sets On characteristic and this device uses Active)
- In method addHumidityCallbackToQueue, what is the purpose of initialising those values? I would remove that completely and initialise state.currentHumidity = 0 at the constructor level. If you don't have a device or file to initialise the humidity, then it should be 0 since the beginning.

```
// Use hardcoded values if not using Humidity values 
    if(config.noHumidity){
      state.currentHumidity = 35
      state.targetHumidity = 5

      if (state.targetState === Characteristic.TargetHumidifierDehumidifierState.HUMIDIFIER) {
        state.currentHumidity = 5
        state.targetHumidity = 15
      } 
...
```

**Comment by kiwi-cam** [comment]
I've had another overhaul with your advice @CyberMrProper . Could you try out 4.3.6-beta.4?

**Comment by CyberMrProper** [comment]
Hi @kiwi-cam the code looks really clean, good work! However, still facing some issues to iron out, here are my findings:
- With option **noHumidity: true** the accessory is unresponsive from the beginning. I had to remove the if condition in the constructor and call this.monitorHumidity(); directly to make the accessory start responding. Not sure what's the right fix for this, maybe refreshing CurrentHumidity UI characteristic?
-  humidifier-dehumidifier.js#L157 >> there is a syntax error, remove the dot before state: **.state.HumidifierThreshold = 100**
- humidifier-dehumidifier.js#L139. >> **if (state.switchState === false) {** switchState most of the time is coming as 0, and that condition fails, since it checks for the type as well. This is causing "HK text status" to be **rising/set** instead of **off**.
- **"enableAutoOff": true** >> still not working, humidifier-dehumidifier.js#L48 call is not needed, what I did in order to make it work,** but not sure if it's the best approach**, was to override the method and correct the property:
```
async checkAutoOff () {
    await catchDelayCancelError(async () => {
      const { config, log, name, state, serviceManager } = this;
      let { disableAutomaticOff, enableAutoOff, onDuration } = config;

      if (state.switchState && enableAutoOff) {
        log(`${name} setSwitchState: (automatically turn off in ${onDuration} seconds)`);

        this.autoOffTimeoutPromise = delayForDuration(onDuration);
        await this.autoOffTimeoutPromise;

        serviceManager.setCharacteristic(Characteristic.On, false);  
                                          ^^ this should be Characteristic.Active instead of On
      }
    });
  }
```
- A big ask, but it would be great if you could include updateHumidityFromFile option, so I can play and test with different current humidity values.

Thanks for your effort!

**Comment by kiwi-cam** [comment]
Nice reports @CyberMrProper - thanks for being my guinea pig!

I've worked through your list and I think I've ticked them all off - even the last one.  Try out homebridge-broadlink-rm-pro@4.3.6-beta.5 and let me know what bugs we've got left :-)

**Comment by CyberMrProper** [comment]
@kiwi-cam most of the issues are gone now. However, enableAutoOff has proven to be hard to fix and still remains:

- Even though you added logic to impact Active property, it seems that is not working

In switch.js >> checkAutoOff I added the following log:
```
let chacteristicName = this.serviceManager.characteristics.switchState.On ? Characteristic.On : Characteristic.Active;
log('chacteristicName: ' + chacteristicName);
```
And I got **On instead of Active**:
```
[11/5/2020, 10:42:54 AM] [Broadlink RM] chacteristicName: function On() {
        var _this = _super.call(this, 'On', On.UUID) || this;
        _this.setProps({
            format: "bool" /* BOOL */,
            perms: ["pr" /* READ */, "pw" /* WRITE */, "ev" /* NOTIFY */]
        });
        _this.value = _this.getDefaultValue();
        return _this;
    }
HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BD-0000-1000-8000-0026BB765291. Adding anyway.
```

- Another issue, but not a big deal, is when I add the device to HK from scratch, it does not work properly until I go inside the tile and hit the on/off button. After that, it starts working properly, even when I restart homebridge. Check attached video: 

![RPReplay_Final1604567993](https://user-images.githubusercontent.com/63667331/98225568-24804780-1f55-11eb-91ca-e563de7a1f76.gif)

**Comment by kiwi-cam** [comment]
Thanks @CyberMrProper I think I've cracked the AutoOn/AutoOff function. It took an overhaul of the Fans but seems to be working now.  The second point.... I'm not seeing the issue. I think it's just that the target humidity is 0% by default so the humidifier is idle.  Let me know if I've missed something there.

Sorry #74 and #85 (CC @masterfordev, @jerzytraczynski, and @apexad), in order to fix AutoOn/AutoOff for Fans and (via inheritance) the HumidiferDehumidifier I've had to revise the Fan type depending on SwingMode logic. The different On/Active characteristic between the two types was unmanageable with the additional logic. I've added a new type "fanv1" to support the additional icons that started that issue.

The new BETA is homebridge-broadlink-rm-pro@4.3.6-beta.6.

**Comment by CyberMrProper** [comment]
It’s working great now! Thank u so much, I’ll let you know if I find any additional issue.

**Comment by masterfordev** [comment]
> Thanks @CyberMrProper I think I've cracked the AutoOn/AutoOff function. It took an overhaul of the Fans but seems to be working now. The second point.... I'm not seeing the issue. I think it's just that the target humidity is 0% by default so the humidifier is idle. Let me know if I've missed something there.
> 
> Sorry #74 and #85 (CC @masterfordev, @jerzytraczynski, and @apexad), in order to fix AutoOn/AutoOff for Fans and (via inheritance) the HumidiferDehumidifier I've had to revise the Fan type depending on SwingMode logic. The different On/Active characteristic between the two types was unmanageable with the additional logic. I've added a new type "fanv1" to support the additional icons that started that issue.
> 
> The new BETA is homebridge-broadlink-rm-pro@4.3.6-beta.6.

Its ok, no worries. Just you forgot add that note in the Readme. And maybe you should add the info about `"isRM4": value,` too. 

Thanks, will test the new beta.

**Comment by apexad** [comment]
fanv1 should be fine.

**Comment by kiwi-cam** [comment]
Fixed in 4.3.6

**Comment by apexad** [comment]
@kiwi-cam fanv1 should have fanSpeed just like the normal fan accessory.  No swing mode or anything else though (like lock controls).

**Comment by kiwi-cam** [comment]
Doh! Would you mind confirming this is sorted in homebridge-broadlink-rm-pro@4.3.7-beta.0?

**Comment by apexad** [comment]
sorted!

**Comment by kiwi-cam** [comment]
4.3.7 fixes this
